services:
  develop:
    image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    volumes:
      - ../../:/workspace:cached
    tty: true

  mysql:
    image: mysql:9.0.1
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_bin"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
